### ISSUE TITLE
New Design for iframe on new website

### ISSUE THREAD

**Issue by benbruscella** [payapps/roi-calculator#1]
- [ ] New designs - https://www.figma.com/file/dXLzLQx26due8wagaIukza/ROI-Calculator?node-id=421%3A3
- [ ] To be run standalone and as an embed iframe
- [ ] Deployed using github pages

```
<iframe src="https://benbruscella.github.io/payapps-roi-calculator?r=au" width="100%" height="100%" frameborder="0"></iframe>
```
[Current State.pdf](https://github.com/payapps/roi-calculator/files/6261519/Current.State.pdf)

**Comment by hlats** [comment]
New design deployed
