### ISSUE TITLE
Updates from Marketing

### ISSUE THREAD

**Issue by benbruscella** [payapps/roi-calculator#2]
@Sam Hlats a couple of small changes if possible:

- [ ] could we make the "ROI month timeframe" just to 1 decimal point
- [ ] with the "annual saving" figure, it needs to also subtract the Payapps annual fee figure from the "before Payapps" amount (e.g. if I'm a tier 3 builder - the annual fee is $36,000 - and using the default figures, the calculator currently gives me an annual saving of $225,000, but actually should be $189,000

**Comment by hlats** [comment]
Fixed and deployed changes.
